# dependencies = {'Son' : 'Father'}
dependencies = {
'rocblas':[],
'rocrand':[],
'rocprim':[],
'rocsolver':['rocblas'],
'rocsparse':['rocprim'],
'rocfft':['rocrand'],
'rocalution':['rocblas','rocrand','rocsparse'],
'rocwmma':['rocblas'],
'rocthrust':['rocprim'],
'rccl':[],
'rocm-cmake':[],
'hipblas':['rocsolver'],
'hipsparse': ['rocsparse'],
'hipsolver':['rocm-cmake','rocsolver'],
'hipcub':['rocprim'],
'hipfort':[],
'miopen':['rocblas','miopengemm','rocm-cmake'],
'miopengemm':[],
'mivisionx':['miopen','rocblas'],
'amdmigraphx':['miopen','rocblas'],
'tensorflow':['miopen','rccl','rocfft','hipblas'],
'pytorch':['rccl','rocfft','hipblas','rocthrust','rocsparse','hipcub'],
'torchvision':['pytorch'],
}