# dependencies2 = {'Father' : 'Son'}

'''dependencies = {
'rocblas':['rocalution','rocsolver','hipblas','rocmvalidationsuite','miopen','rocwmma','mivisionx','amdgraphx','tensorflow','pytorch'],
'rocrand':['rocfft','rocalution','tensorflow','pytorch'],
'rocprim':['rocsparse','hipsparse','rocalution','rocthrust','hipcub','pytorch'],
'rocsolver':['hipsolver','hipblas'],
'rocsparse':['hipsparse','rocalution','pytorch'],
'rocfft':['tensorflow','pytorch'],
'rocalution':[],
'rocwmma':[],
'rocthrust':['pytorch'],
'rccl':['tensorflow','pytorch'],
'rocm-cmake':['hipsolver','miopen'],
'rocmvalidationsuite':[],
'hipblas':['tensorflow','pytorch'],
'hipsparse':[],
'hipsolver':[],
'hipcub':['pytorch'],
'hipfort':[],
'miopen':['mivisionx','amdgraphx','tensorflow'],
'miopengemm':['miopen'],
'mivisionx':[],
'amdgraphx':[],
'tensorflow':[],
'pytorch':['torchvision'],
'torchvision':[],
}'''

dependencies = {
'rocblas':['rocalution','rocsolver','rocmvalidationsuite','miopen','rocwmma'],
'rocrand':['rocfft','rocalution'],
'rocprim':['rocsparse','rocthrust','hipcub'],
'rocsolver':['hipsolver','hipblas'],
'rocsparse':['hipsparse','rocalution','pytorch'],
'rocfft':['tensorflow','pytorch'],
'rocalution':[],
'rocwmma':[],
'rocthrust':['pytorch'],
'rccl':['tensorflow','pytorch'],
'rocm-cmake':['hipsolver','miopen'],
'rocmvalidationsuite':[],
'hipblas':['tensorflow','pytorch'],
'hipsparse':[],
'hipsolver':[],
'hipcub':['pytorch'],
'hipfort':[],
'miopen':['mivisionx','amdgraphx','tensorflow'],
'miopengemm':['miopen'],
'mivisionx':[],
'amdgraphx':[],
'tensorflow':[],
'pytorch':['torchvision'],
'torchvision':[],
}